general:
  num_consumers: 1
  num_producers: 1
  num_brains: 1

razzler_brain:
  commands:
    - ping
    - react
    - summon
    - see_image
    - create_image
  admins:
    - "+441234567890"
  max_chat_history_tokens: 1000

openai:
  fast_model: gpt-3.5-turbo
  quality_model: gpt-4-turbo
  vision_model: gpt-4o
  image_model: dall-e-3

  chat_completion_kwargs:
    temperature: 1.0
    max_tokens: 400
    n: 1

  vision_completion_kwargs:
    max_tokens: 80

  image_generation_kwargs:
    size: 256x256
    style: vivid
    quality: standard
    n: 1

signal:
  signal_service: localhost:port
  phone_number: "+441234567890"
  admin_number: "+441234567890"
  message_history_length: 1000

redis:
  host: localhost
  port: 6379
  password: password
  db: 0

rabbitmq:
  host: localhost
  port: 5672
  login: guest
  password: guest
